---
- name: ping all
  hosts: all 
  gather_facts: false
  connection: local

  vars:
    cli:
     username: user1234
     password: paSSword
     timeout: 999999
  tasks:
    - name: ping all
      ios_command:
        provider: "{{ cli }}"
        commands: 
         - ping 10.##.#.255
         - ping 10.##.##.255
         - ping 10.##.##.255
      register: output

    - name: show output
      debug:
        var: output.stdout
...

