---
- name: show all
  hosts: all 
  gather_facts: false
  connection: network_cli

  tasks:
    - name: show all
      ios_command:
        commands: 
         - show run   
         - show int status
         - show int trunk
         - show vlan br
         - show version

      register: output

    - name: show output
      debug:
        var: output.stdout
...

